name: Deploy NextTool

on:
  push:
    branches:
      - main # main 分支 push 时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ 安装 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3️⃣ 安装依赖
      - name: Install dependencies
        run: npm install

      # 4️⃣ 构建项目
      - name: Build project
        run: npm run build

      # 5️⃣ 调试构建文件
      - name: Debug build output
        run: |
          echo "当前目录: $(pwd)"
          ls -la
          ls -la .next
          ls -la package.json
          ls -la ecosystem.config.js

      # 6️⃣ 上传构建产物到服务器（使用仓库根目录路径）
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ".next package.json ecosystem.config.js"
          target: "/var/www/tool"
          overwrite: true
          debug: true
          working-directory: "/home/runner/work/tool/tool"

      # 7️⃣ 重启或启动 PM2 服务
      - name: Restart PM2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/tool
            ls -la   # 查看上传文件
            pm2 restart next-app || pm2 start ecosystem.config.js
