name: Deploy NextTool

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建
      - name: Build project
        run: npm run build

      # 5. 调试：确认文件存在
      - name: Debug build output
        run: |
          echo "当前目录: $(pwd)"
          ls -la
          ls -la .next || echo ".next 不存在"
          test -f package.json && echo "package.json 存在" || echo "package.json 不存在"
          test -f ecosystem.config.js && echo "ecosystem.config.js 存在" || echo "ecosystem.config.js 不存在"

      # 6. 上传构建结果 + 配置
      - name: Upload to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          target: "/var/www/tool"
          overwrite: true
          debug: true
          source: |
            .next
            package.json
            ecosystem.config.js

      # 7. 重启 PM2（用 ssh-action）
      - name: Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/tool
            npm install --production
            pm2 restart next-app || pm2 start ecosystem.config.js
