name: Deploy NextTool

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. 安装依赖
      - name: Install dependencies
        run: npm install

      # 4. 构建 Next.js
      - name: Build project
        run: npm run build

      # 5. 调试：确认文件存在
      - name: Debug build output
        run: |
          echo "当前目录: $(pwd)"
          ls -la
          test -d .next && echo ".next 存在" || echo ".next 不存在"
          test -f package.json && echo "package.json 存在" || echo "package.json 不存在"
          test -f ecosystem.config.js && echo "ecosystem.config.js 存在" || echo "ecosystem.config.js 不存在"

      # 6. 打包需要的文件
      - name: Package build files
        run: |
          tar -czf deploy.tar.gz .next package.json ecosystem.config.js
          ls -la deploy.tar.gz

      # 7. 上传 tar 包到服务器
      - name: Upload tarball to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "deploy.tar.gz"
          target: "/var/www/tool"
          overwrite: true
          debug: true

      # 8. 在服务器解压并部署
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/tool
            tar -xzf deploy.tar.gz
            rm deploy.tar.gz
            npm install --production
            pm2 restart next-app || pm2 start ecosystem.config.js
